### ISSUE TITLE
Wrong path /Users/txus/projects/webview-plus/`

### ISSUE THREAD

**Issue by hoetmaaiers** [ludei/cocoonjs-cli#17]
When I do `cocoonjs plugin add com.ludei.webview.plus`
, I get the following error.

```
Cannot install the WebView+ in your project, failed to execute the command `cocoonjs plugin add /Users/txus/projects/webview-plus/`. 
```

It seems the path is set wrong to a fixed user `/User/txus/...`

**Comment by LibelulaV** [comment]
Hello,

As this was fixed long ago, I will close the issue. 

Cheers :).
