### ISSUE TITLE
[CocoonJS] Cannot build Webview+ project

### ISSUE THREAD

**Issue by bishoplee** [ludei/cocoonjs-cli#24]
Hello Ludei,

I'm having a similar issue with my installation for a cordova project. Code is below:

Bishoplee:my_app bishoplee$ cocoonjs plugin add com.ludei.webview.plus -d
[CocoonJS] Executing command 'plugin add com.ludei.webview.plus -d'
[CocoonJS] Installing Webview+ in your Cordova Project.
[CocoonJS] Downloading Webview+...
Fetching plugin "com.ludei.webview.plus" via npm
Fetching plugin "com.ludei.webview.plus" via cordova plugins registry
Installing "com.ludei.webview.plus" for android
[CocoonJS] Executing 'ant release -buildfile /Users/bishoplee/apps/my_app/plugins/com.ludei.webview.plus/android/build.xml'
[CocoonJS] Cannot build Webview+ project

Please what am I doing wrong.

Thank you.

**Comment by BlueSialia** [comment]
Hi @bishoplee,

You must know that this project is deprecated. It only worked with our old cloud.

Please, use our new cloud: <http://cocoon.io>
