### ISSUE TITLE
Command "cocoonjs plugin add com.ludei.webview.plus" is failing

### ISSUE THREAD

**Issue by josedevega** [ludei/cocoonjs-cli#25]
C:\Users\jvega\Documents\Cocoon\MyProject>cocoonjs -v
1.0.0-0.9.0

C:\Users\jvega\Documents\Cocoon\MyProject>cocoonjs info
[CocoonJS] No valid command found. Try --help for a list of all the available commands.

C:\Users\jvega\Documents\Cocoon\MyProject>cocoonjs platform
[CocoonJS] Executing command 'platform'
[CocoonJS] Installed platforms:
  android 6.1.2
  browser 4.1.0
  ios 4.3.1
  windows 4.4.3
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  firefoxos ~3.6.3
  webos ~3.7.0
  wp8 ~3.8.2 (deprecated)
[CocoonJS]

C:\Users\jvega\Documents\Cocoon\MyProject>cocoonjs plugin add com.ludei.webview.plus --verbose
[CocoonJS] Executing command 'plugin add com.ludei.webview.plus --verbose'
[CocoonJS] Installing Webview+ in your Cordova Project.
[CocoonJS] Downloading Webview+...
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.ludei.webview.plus
[CocoonJS] Cannot install the WebView+ in your project, failed to execute the command `cocoonjs plugin add com.ludei.webview.plus`.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.ludei.webview.plus

**Comment by BlueSialia** [comment]
I'm sorry, this project is discontinued and there wasn't a proper warning in the README.
